export enum Errors {
  BAD_EMAIL = 'BAD_EMAIL',
  FIELD_IS_EMPTY = 'FIELD_IS_EMPTY',
  PASSWORD_IS_SHORTS = 'PASSWORD_IS_SHORTS',
  USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  BAD_CREDENTIAL = 'BAD_CREDENTIAL',
}
