export enum Errors {
  BAD_EMAIL = 'BAD_EMAIL',
  FIELD_IS_EMPTY = 'FIELD_IS_EMPTY',
  PASSWORD_IS_SHORTS = 'PASSWORD_IS_SHORTS',
  USER_ALREADY_EXIST = 'USER_ALREADY_EXIST',
  INVITE_ALREADY_EXIST = 'INVITE_ALREADY_EXIST',
  INVITE_CODE_EXPIRED = 'INVITE_CODE_EXPIRED',
  INVITE_CODE_NOTE_FOUND = 'INVITE_CODE_NOTE_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXIST_IN_ORGANIZATION = 'USER_ALREADY_EXIST_IN_ORGANIZATION',
  BAD_CREDENTIAL = 'BAD_CREDENTIAL',
}
